[package]
name = "tetris"
version = "0.1.0"
authors = ["BWbwchen <tim.chenbw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.0"
rand = "0.8.3"
mint = "0.5.1"
